airline/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    path,
    include
)

from airline.settings import base

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("management.urls", namespace="management")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls"))
] + static(base.STATIC_URL, document_root=base.STATIC_ROOT)

management/urls.py
from django.urls import path

from management.views import (
    index,
    FlightListView,
    StaffListView,
    PlaneListView,
    AirportListView,
    AirportDetailView,
    PlaneDetailView,
    StaffDetailView,
    FlightDetailView,
    AirportCreateView,
    PlaneCreateView,
    StaffCreateView,
    FlightCreateView,
    AirportUpdateView,
    PlaneUpdateView,
    StaffUpdateView,
    FlightUpdateView,
    AirportDeleteView,
    PlaneDeleteView,
    StaffDeleteView,
    FlightDeleteView,
    toggle_assign_to_plane,
    toggle_assign_to_airport,
    change_password
)


urlpatterns = [
    path("", index, name="index"),
    path(
        "airports/",
        AirportListView.as_view(),
        name="airports"
    ),
    path(
        "airports/<int:pk>/",
        AirportDetailView.as_view(),
        name="airport-detail"
    ),
    path(
        "airports/create/",
        AirportCreateView.as_view(),
        name="airport-create"
    ),
    path(
        "airports/<int:pk>/update/",
        AirportUpdateView.as_view(),
        name="airport-update"
    ),
    path(
        "airports/<int:pk>/delete/",
        AirportDeleteView.as_view(),
        name="airport-delete"
    ),
    path(
        "planes/",
        PlaneListView.as_view(),
        name="planes"
    ),
    path(
        "planes/<int:pk>/",
        PlaneDetailView.as_view(),
        name="plane-detail"
    ),
    path(
        "planes/create/",
        PlaneCreateView.as_view(),
        name="plane-create"
    ),
    path(
        "planes/<int:pk>/update/",
        PlaneUpdateView.as_view(),
        name="plane-update"
    ),
    path(
        "planes/<int:pk>/delete/",
        PlaneDeleteView.as_view(),
        name="plane-delete"
    ),
    path(
        "staff/",
        StaffListView.as_view(),
        name="staff"
    ),
    path(
        "staff/<int:pk>/",
        StaffDetailView.as_view(),
        name="staff-detail"
    ),
    path(
        "staff/create/",
        StaffCreateView.as_view(),
        name="staff-create"
    ),
    path(
        "staff/<int:pk>/update/",
        StaffUpdateView.as_view(),
        name="staff-update"
    ),
    path(
        "staff/<int:pk>/delete/",
        StaffDeleteView.as_view(),
        name="staff-delete"
    ),
    path(
        "flights/",
        FlightListView.as_view(),
        name="flights"
    ),
    path(
        "flights/<int:pk>/",
        FlightDetailView.as_view(),
        name="flight-detail"
    ),
    path(
        "flights/create/",
        FlightCreateView.as_view(),
        name="flight-create"
    ),
    path(
        "flights/<int:pk>/update",
        FlightUpdateView.as_view(),
        name="flight-update"
    ),
    path(
        "flights/<int:pk>/delete/",
        FlightDeleteView.as_view(),
        name="flight-delete"
    ),
    path(
        "planes/<int:pk>/toggle/",
        toggle_assign_to_plane,
        name="toggle-assign-to-plane"
    ),
    path(
        "airports/<int:pk>/toggle/",
        toggle_assign_to_airport,
        name="toggle-assign-to-airport"
    ),
    path(
        "staff/<int:pk>/password",
        change_password,
        name="password"
    )
]

app_name = "management"

management/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm
)
from django.core.exceptions import ValidationError

from management.models import (
    Airport,
    Staff,
    Plane,
    Flight
)


class AirportForm(forms.ModelForm):
    class Meta:
        model = Airport
        fields = "__all__"


def validate_licence_number(
        licence_number,
):
    if len(licence_number) != 8:
        raise ValidationError(
            "Licence number should consist of 8 characters"
        )
    elif not all(
            char.isupper() and char.isalpha()
            for char in licence_number[:3]
    ):
        raise ValidationError(
            "First 3 characters should be uppercase letters"
        )
    elif not licence_number[3:].isdigit():
        raise ValidationError(
            "Last 5 characters should be digits"
        )

    return licence_number


class StaffForm(forms.ModelForm):
    allowed_airports = forms.ModelMultipleChoiceField(
        queryset=Airport.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    allowed_planes = forms.ModelMultipleChoiceField(
        queryset=Plane.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Staff
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "phone_number",
            "licence_number",
            "position",
            "total_hours",
            "allowed_planes",
            "allowed_airports"
        ]

    def clean_licence_number(self):
        licence_number = self.cleaned_data.get("licence_number")
        return validate_licence_number(licence_number)


class StaffCreateForm(UserCreationForm, StaffForm):
    class Meta(StaffForm.Meta):
        model = Staff
        fields = StaffForm.Meta.fields + ["password1", "password2"]


class StaffUpdateForm(StaffForm):
    class Meta(StaffForm.Meta):
        model = Staff
        fields = StaffForm.Meta.fields


class StaffChangePasswordForm(UserChangeForm):
    model = Staff


class PlaneForm(forms.ModelForm):
    class Meta:
        model = Plane
        fields = "__all__"
        widgets = {
            "last_maintenance": AdminDateWidget(
                attrs={"type": "date"},
            )
        }


def validate_flight(data: dict):
    for staff_member in data.get("staff"):
        if not data.get("plane") in staff_member.allowed_planes.all():
            raise ValidationError(
                f"{staff_member} cannot fly on {data.get("plane")}"
            )
        if not data.get("departure") in staff_member.allowed_airports.all():
            raise ValidationError(
                f"{staff_member} cannot fly from {data.get("departure")}"
            )
        if not data.get("destination") in staff_member.allowed_airports.all():
            raise ValidationError(
                f"{staff_member} cannot fly to {data.get("destination")}"
            )
    takeoff = data.get("takeoff")
    landing = data.get("landing")
    if takeoff and landing and landing <= takeoff:
        raise ValidationError(
            "Landing must be after takeoff."
        )
    return data


class FlightForm(forms.ModelForm):
    staff = forms.ModelMultipleChoiceField(
        queryset=Staff.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Flight
        fields = [
            "flight_number",
            "plane",
            "departure",
            "destination",
            "takeoff",
            "landing",
            "staff",
            "status"
        ]
        widgets = {
            "takeoff": forms.DateTimeInput(
                attrs={"type": "datetime-local"}
            ),
            "landing": forms.DateTimeInput(
                attrs={"type": "datetime-local"}
            ),
        }

    def clean(self):
        cleaned_data = super().clean()
        validate_flight(cleaned_data)
        return cleaned_data


class AirportSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={"placeholder": "Search by airport name"}
        ),
        required=False,
        label="",
    )


class PlaneSearchForm(forms.Form):
    model = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={"placeholder": "Search by plane model"}
        ),
        required=False,
        label="",
    )


class FlightSearchForm(forms.Form):
    flight_number = forms.CharField(
        max_length=10,
        widget=forms.TextInput(
            attrs={"placeholder": "Search by flight number"}
        ),
        required=False,
        label="",
    )


class StaffSearchForm(forms.Form):
    last_name = forms.CharField(
        max_length=255,
        widget=forms.TextInput(
            attrs={"placeholder": "Search by last name"}
        ),
        required=False,
        label="",
    )

management/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404
)
from django.urls import reverse_lazy
from django.views import generic

from management.forms import (
    AirportForm,
    PlaneForm,
    FlightForm,
    AirportSearchForm,
    PlaneSearchForm,
    FlightSearchForm,
    StaffSearchForm,
    StaffCreateForm,
    StaffUpdateForm
)
from management.models import (
    Airport,
    Plane,
    Flight,
    Staff
)


# Create your views here.

@login_required
def index(request):
    num_airports = Airport.objects.count()
    num_planes = Plane.objects.count()
    num_staff = Staff.objects.count()
    num_flights = Flight.objects.count()
    num_visits = request.session.get("num_visits", 1)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_airports": num_airports,
        "num_planes": num_planes,
        "num_staff": num_staff,
        "num_flights": num_flights,
        "num_visits": num_visits,
    }

    return render(request, "management/index.html", context=context)


class AirportListView(LoginRequiredMixin, generic.ListView):
    model = Airport
    paginate_by = 5

    def get_context_data(
        self, *, object_list=None, **kwargs
    ):
        context = super(AirportListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = AirportSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Airport.objects.all()
        form = AirportSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class AirportDetailView(LoginRequiredMixin, generic.DetailView):
    model = Airport


class AirportCreateView(LoginRequiredMixin, generic.CreateView):
    model = Airport
    form_class = AirportForm
    success_url = reverse_lazy("management:airports")


class AirportUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Airport
    form_class = AirportForm
    success_url = reverse_lazy("management:airports")


class AirportDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Airport
    success_url = reverse_lazy("management:airports")


class PlaneListView(LoginRequiredMixin, generic.ListView):
    model = Plane
    paginate_by = 5

    def get_context_data(
        self, *, object_list=None, **kwargs
    ):
        context = super(PlaneListView, self).get_context_data(**kwargs)
        model = self.request.GET.get("model", "")
        context["search_form"] = PlaneSearchForm(
            initial={"model": model}
        )
        return context

    def get_queryset(self):
        queryset = Plane.objects.all()
        form = PlaneSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                model__icontains=form.cleaned_data["model"]
            )
        return queryset


class PlaneDetailView(LoginRequiredMixin, generic.DetailView):
    model = Plane


class PlaneCreateView(LoginRequiredMixin, generic.CreateView):
    model = Plane
    form_class = PlaneForm
    success_url = reverse_lazy("management:planes")


class PlaneUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Plane
    form_class = PlaneForm
    success_url = reverse_lazy("management:planes")


class PlaneDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Plane
    success_url = reverse_lazy("management:planes")


class FlightListView(LoginRequiredMixin, generic.ListView):
    model = Flight
    paginate_by = 5

    def get_context_data(
        self, *, object_list=None, **kwargs
    ):
        context = super(FlightListView, self).get_context_data(**kwargs)
        flight_number = self.request.GET.get("flight_number", "")
        context["search_form"] = FlightSearchForm(
            initial={"flight_number": flight_number}
        )
        return context

    def get_queryset(self):
        queryset = Flight.objects.all().select_related(
            "departure",
            "destination",
            "plane"
        )
        form = FlightSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                flight_number__icontains=form.cleaned_data[
                    "flight_number"
                ]
            )
        return queryset


class FlightDetailView(LoginRequiredMixin, generic.DetailView):
    model = Flight


class FlightCreateView(LoginRequiredMixin, generic.CreateView):
    model = Flight
    form_class = FlightForm
    success_url = reverse_lazy("management:flights")


class FlightUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Flight
    form_class = FlightForm
    success_url = reverse_lazy("management:flights")


class FlightDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Flight
    success_url = reverse_lazy("management:flights")


class StaffListView(LoginRequiredMixin, generic.ListView):
    model = Staff
    paginate_by = 5

    def get_context_data(
        self, *, object_list=None, **kwargs
    ):
        context = super(StaffListView, self).get_context_data(**kwargs)
        last_name = self.request.GET.get("last_name", "")
        context["search_form"] = StaffSearchForm(
            initial={"last_name": last_name}
        )
        return context

    def get_queryset(self):
        queryset = Staff.objects.all()
        form = StaffSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                last_name__icontains=form.cleaned_data["last_name"]
            )
        return queryset


class StaffDetailView(LoginRequiredMixin, generic.DetailView):
    model = Staff


class StaffCreateView(LoginRequiredMixin, generic.CreateView):
    model = Staff
    form_class = StaffCreateForm
    success_url = reverse_lazy("management:staff")


class StaffUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Staff
    form_class = StaffUpdateForm
    success_url = reverse_lazy("management:staff")


class StaffDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Staff
    success_url = reverse_lazy("management:staff")


@login_required
def toggle_assign_to_plane(request, pk):
    staff_member = Staff.objects.get(id=request.user.id)
    plane = Plane.objects.get(id=pk)
    if (
        plane in staff_member.allowed_planes.all()
    ):
        staff_member.allowed_planes.remove(plane)
    else:
        staff_member.allowed_planes.add(plane)
    return HttpResponseRedirect(
        reverse_lazy("management:plane-detail", args=[pk])
    )


@login_required
def toggle_assign_to_airport(request, pk):
    staff_member = Staff.objects.get(id=request.user.id)
    airport = Airport.objects.get(id=pk)
    if (
        airport in staff_member.allowed_airports.all()
    ):
        staff_member.allowed_airports.remove(airport)
    else:
        staff_member.allowed_airports.add(airport)
    return HttpResponseRedirect(
        reverse_lazy("management:airport-detail", args=[pk])
    )


@login_required
def change_password(request, pk):
    user = get_object_or_404(Staff, pk=pk)

    if request.method == "POST":
        form = PasswordChangeForm(user=user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, user)  # Keeps user logged in
            messages.success(request, "Password updated successfully.")
            return redirect("management:staff-detail", pk=pk)
    else:
        form = PasswordChangeForm(user=user)

    return render(
        request,
        "management/change_password.html",
        {
            "form": form,
            "staff": user
        }
    )

templates/management/airport_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  <title>Skyway Airlines - Delete an airport?</title>
{% endblock %}

{% block content %}
  <h2 class="header-2">Delete an airport?</h2>
  <form class="form-wrapper" action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'management:airport-detail' pk=airport.id %}" class="btn btn-secondary">
      Cancel
    </a>
  </form>
{% endblock %}

templates/management/airport_detail.html
{% extends "base.html" %}

{% block title %}
  <title>Skyway Airlines - {{ airport.name }}</title>
{% endblock %}

{% block content %}
  <h2 class="header-2">{{ airport.name }}</h2>
  <p class="article">
    City: {{ airport.city }}<br>
    Country: {{ airport.country }}<br>
    Timezone: {{ airport.timezone }}<br>
    Latitude: {{ airport.latitude }}<br>
    Longitude: {{ airport.longitude }}<br>
  </p>
  {% if airport in user.allowed_airports.all %}
    <p class="paragraph">
      You are currently allowed to use this airport. Do you want to remove it from your allowed list?
      <a href="{% url 'management:toggle-assign-to-airport' pk=airport.id %}" class="btn btn-secondary">
        Remove from allowed airports
      </a>
    </p>
  {% else %}
    <p class="paragraph">
      You are not allowed to use this airport yet. Do you want to add it to your allowed list?
      <a href="{% url 'management:toggle-assign-to-airport' pk=airport.id %}" class="btn btn-secondary">
        Add to allowed airports
      </a>
    </p>
  {% endif %}
  <a href="{% url 'management:airport-update' pk=airport.id %}" class="btn btn-secondary">
    Update airport
  </a>

  <a href="{% url 'management:airport-delete' pk=airport.id %}" class="btn btn-secondary btn-danger">
    Delete airport
  </a>
{% endblock %}

templates/management/airport_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  <title>Skyway Airlines - {{ object|yesno:"Update,Create" }} an airport</title>
{% endblock %}

{% block content %}
  <h2 class="header-2">{{ object|yesno:"Update,Create" }} an airport</h2>
  <form class="form-wrapper" action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/management/flight_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  <title>Skyway Airlines - Delete a flight?</title>
{% endblock %}

{% block content %}
  <h2 class="header-2">Delete a flight?</h2>

  <form class="form-wrapper" action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'management:flight-detail' pk=flight.id %}" class="btn btn-secondary">
      Cancel
    </a>
  </form>
{% endblock %}

templates/management/flight_detail.html
{% extends "base.html" %}

{% block title %}
  <title>Skyway Airlines - Flight {{ flight.flight_number}}</title>
{% endblock %}

{% block content %}
  <h2 class="header-2">{{ flight.flight_number }}</h2>
  <p class="article">
    Plane: {{ flight.plane }}<br>
    Departure: {{ flight.departure }} {{ flight.takeoff }}<br>
    Destination: {{ flight.destination }} {{ flight.landing }}<br>
    Status: {{ flight.status }}</p> {# change text color for different statuses #}
  <h3 class="header-3">Staff:</h3>
  <ul class="article-ul">
  {% for staff in flight.staff.all %}
    <li>
    {{ staff }}
    </li>
  {% endfor %}
  </ul>
  <a href="{% url 'management:flight-update' pk=flight.id %}" class="btn btn-secondary link-to-page">
    Update
  </a>
  <a href="{% url 'management:flight-delete' pk=flight.id %}" class="btn btn-danger link-to-page">
    Delete
  </a>

{% endblock %}

templates/management/flight_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  <title>Skyway Airlines - {{ object|yesno:"Update,Create" }} a flight</title>
{% endblock %}

{% block content %}
  <h2 class="header-2">{{ object|yesno:"Update,Create" }} a flight</h2>
  <form class="form-wrapper" action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/management/flight_list.html
{% extends "base.html" %}

{% block title %}
  <title>Skyway Airlines - Flights</title>
{% endblock %}

{% block content %}
  <h2 class="header-2">
    Flight List
  </h2>
  <a href="{% url 'management:flight-create' %}" class="btn btn-primary btn-add">
    Add a flight
  </a>
  {% include "includes/search_form.html" %}
  {% if flight_list %}
  <table class="table">
  <tr>
    <th>Flight Number</th>
    <th>Plane</th>
    <th>Departure</th>
    <th>Takeoff</th>
    <th>Destination</th>
    <th>Landing</th>
    <th>Status</th>
  </tr>
  {% for flight in flight_list %}
    <tr>
      <td><a href="{% url 'management:flight-detail' pk=flight.id %}">{{ flight.flight_number }}</a></td>
      <td>{{ flight.plane }}</td>
      <td>{{ flight.departure }}</td>
      <td>{{ flight.takeoff }}</td>
      <td>{{ flight.destination }}</td>
      <td>{{ flight.landing }}</td>
      <td>{{ flight.status }}</td>
    </tr>
  {% endfor %}
  </table>
  {% else %}
    <p>No flights found.</p>
  {% endif %}
{% endblock %}

templates/management/index.html
{% extends "base.html" %}

{% block title %}
  <title>Skyway Airlines</title>
{% endblock %}

{% block hero-content %}
  <section class="section hero" id="home" aria-label="home">
    <div class="hero-text">
      <h1 class="header-1">Skyway Airlines</h1>
      <h2 class="header-2">Welcome to Skyway Airlines!</h2>
    </div>
  </section>
{% endblock %}
{% block content %}
  <h2 class="header-2">The airline has the following record counts:</h2>
  <p class="article">
    <strong>Airports:</strong> {{ num_airports }}<br>
    <strong>Planes:</strong> {{ num_planes }}<br>
    <strong>Staff:</strong> {{ num_staff }}<br>
    <strong>Flights:</strong> {{ num_flights }}<br>
    You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>
{% endblock %}

templates/management/plane_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  <title>Skyway Airlines - Delete a plane?</title>
{% endblock %}

{% block content %}
  <h2 class="header-2">Delete plane?</h2>
  <form class="form-wrapper" action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'management:plane-detail' pk=plane.id %}" class="btn btn-secondary">
      Cancel
    </a>
  </form>
{% endblock %}

templates/management/plane_detail.html
{% extends "base.html" %}

{% block title %}
  <title>Skyway Airlines - {{ plane.model }} ({{ plane.registration }})</title>
{% endblock %}

{% block content %}
  <h2 class="header-2">{{ plane.model }}</h2>
  <p class="article">
    Registration: {{ plane.registration }}<br>
    Capacity: {{ plane.capacity }}<br>
    Last maintenance: {{ plane.last_maintenance }}<br>
    Hours to maintenance: {{ plane.hours_to_maintenance }}<br>
    Total hours: {{ plane.total_hours }}
  </p>

  {% if plane in user.allowed_planes.all %}
    <p class="paragraph">
      You are currently allowed to use this plane. Do you want to remove it from your allowed list?
      <a href="{% url 'management:toggle-assign-to-plane' pk=plane.id %}" class="btn btn-secondary">
        Remove from allowed planes
      </a>
    </p>
  {% else %}
    <p class="paragraph">
      You are not allowed to use this plane yet. Do you want to add it to your allowed list?
      <a href="{% url 'management:toggle-assign-to-plane' pk=plane.id %}" class="btn btn-secondary">
        Add to allowed planes
      </a>
    </p>
  {% endif %}

  <a href="{% url 'management:plane-update' pk=plane.id %}" class="btn btn-secondary">
    Update plane
  </a>
  <a href="{% url 'management:plane-delete' pk=plane.id %}" class="btn btn-danger">
    Delete plane
  </a>
{% endblock %}

templates/management/plane_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  <title>Skyway Airlines - {{ object|yesno:"Update,Create" }} a plane</title>
{% endblock %}

{% block content %}
  <h2 class="header-2">{{ object|yesno:"Update,Create" }} a plane</h2>
  <form class="form-wrapper" action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/management/staff_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  <title>Skyway Airlines - Delete a staff member?</title>
{% endblock %}

{% block content %}
  <h2 class="header-2">Delete a staff member?</h2>
  <form class="form-wrapper" action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'management:staff-detail' pk=staff.id %}" class="btn btn-secondary">
      Cancel
    </a>
  </form>
{% endblock %}

templates/management/staff_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  <title>Skyway Airlines - {{ object|yesno:"Update,Create" }} a staff member</title>
{% endblock %}

{% block hero-content %}
  {% endblock %}

{% block content %}
  <h2 class="header-2">{{ object|yesno:"Update,Create" }} a staff member</h2>
  <form class="form-wrapper" action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    {% if object %}
      <a class="btn btn-secondary" href="{% url 'management:staff' %}">Cancel</a>
      <a class="btn btn-primary" href="{% url 'management:password' object.pk %}">Change password</a>
    {% endif %}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

templates/management/staff_list.html
{% extends "base.html" %}

{% block title %}
  <title>Skyway Airlines - Staff</title>
{% endblock %}

{% block content %}
  <h2 class="header-2">
    Staff List
  </h2>
  <a href="{% url 'management:staff-create' %}" class="btn btn-primary btn-add">
    Add a staff member
  </a>
  {% include "includes/search_form.html" %}
  {% if staff_list %}
  <table class="table">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Position</th>
    <th>Phone number</th>
    <th>E-mail</th>
    <th>Total hours</th>
  </tr>
  {% for staff in staff_list %}
    <tr>
      <td>{{ staff.first_name }}</td>
      <td>
        <a href="{% url 'management:staff-detail' pk=staff.id %}">
          {{ staff.last_name }}
          {% if user == staff %}
            (Me)
          {% endif %}
        </a>
      </td>
      <td>{{ staff.position }}</td>
      <td>{{ staff.phone_number }}</td>
      <td>{{ staff.email }}</td>
      <td>{{ staff.total_hours }}</td>
    </tr>
  {% endfor %}
  </table>
  {% else %}
    <p>No employees found.</p>
  {% endif %}
{% endblock %}