airline/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    path,
    include
)

from airline.settings import base

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("management.urls", namespace="management")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls"))
] + static(base.STATIC_URL, document_root=base.STATIC_ROOT)

management/urls.py
from django.urls import path

from management.views import (
    index,
    FlightListView,
    StaffListView,
    PlaneListView,
    AirportListView,
    AirportDetailView,
    PlaneDetailView,
    StaffDetailView,
    FlightDetailView,
    AirportCreateView,
    PlaneCreateView,
    StaffCreateView,
    FlightCreateView,
    AirportUpdateView,
    PlaneUpdateView,
    StaffUpdateView,
    FlightUpdateView,
    AirportDeleteView,
    PlaneDeleteView,
    StaffDeleteView,
    FlightDeleteView,
    toggle_assign_to_plane,
    toggle_assign_to_airport,
    change_password
)


urlpatterns = [
    path("", index, name="index"),
    path(
        "airports/",
        AirportListView.as_view(),
        name="airports"
    ),
    path(
        "airports/<int:pk>/",
        AirportDetailView.as_view(),
        name="airport-detail"
    ),
    path(
        "airports/create/",
        AirportCreateView.as_view(),
        name="airport-create"
    ),
    path(
        "airports/<int:pk>/update/",
        AirportUpdateView.as_view(),
        name="airport-update"
    ),
    path(
        "airports/<int:pk>/delete/",
        AirportDeleteView.as_view(),
        name="airport-delete"
    ),
    path(
        "planes/",
        PlaneListView.as_view(),
        name="planes"
    ),
    path(
        "planes/<int:pk>/",
        PlaneDetailView.as_view(),
        name="plane-detail"
    ),
    path(
        "planes/create/",
        PlaneCreateView.as_view(),
        name="plane-create"
    ),
    path(
        "planes/<int:pk>/update/",
        PlaneUpdateView.as_view(),
        name="plane-update"
    ),
    path(
        "planes/<int:pk>/delete/",
        PlaneDeleteView.as_view(),
        name="plane-delete"
    ),
    path(
        "staff/",
        StaffListView.as_view(),
        name="staff"
    ),
    path(
        "staff/<int:pk>/",
        StaffDetailView.as_view(),
        name="staff-detail"
    ),
    path(
        "staff/create/",
        StaffCreateView.as_view(),
        name="staff-create"
    ),
    path(
        "staff/<int:pk>/update/",
        StaffUpdateView.as_view(),
        name="staff-update"
    ),
    path(
        "staff/<int:pk>/delete/",
        StaffDeleteView.as_view(),
        name="staff-delete"
    ),
    path(
        "flights/",
        FlightListView.as_view(),
        name="flights"
    ),
    path(
        "flights/<int:pk>/",
        FlightDetailView.as_view(),
        name="flight-detail"
    ),
    path(
        "flights/create/",
        FlightCreateView.as_view(),
        name="flight-create"
    ),
    path(
        "flights/<int:pk>/update",
        FlightUpdateView.as_view(),
        name="flight-update"
    ),
    path(
        "flights/<int:pk>/delete/",
        FlightDeleteView.as_view(),
        name="flight-delete"
    ),
    path(
        "planes/<int:pk>/toggle/",
        toggle_assign_to_plane,
        name="toggle-assign-to-plane"
    ),
    path(
        "airports/<int:pk>/toggle/",
        toggle_assign_to_airport,
        name="toggle-assign-to-airport"
    ),
    path(
        "staff/<int:pk>/password",
        change_password,
        name="password"
    )
]

app_name = "management"

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}
    <title>
      SkyWay Airlines
    </title>
  {% endblock %}

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/svg+xml">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet">
  <link rel="preload" as="image" href="{% static 'images/hero-bg.jpg' %}">

</head>

<body id="top">
<header class="header" data-header>
<div class="container">
  <a href="{% url 'management:index' %}">
    <img src="{% static 'images/logo.png' %}" width="202" height="96" alt="logo">
  </a>

  {% block navigation %}
    {% include "includes/navigation.html" %}
  {% endblock %}
</div>
</header>
<main>
    <article>
      {% block hero-content %}
      {% endblock %}
      <section class="section standard-content">
        <div class="container">
          {% block content %}{% endblock %}
          {% block pagination %}
            {% include "includes/pagination.html" %}
          {% endblock %}
        </div>
      </section>

    </article>

  <!--
    - #FOOTER
  -->

  <footer class="footer">
    <div class="container">

      <div class="footer-top section grid-list">

        <div class="footer-brand">

          <a href="{% url 'management:index' %}" class="logo">
            <img src="{% static 'images/logo.png' %}" width="204" height="96" alt="logo">
          </a>

          <p class="footer-text">
            Private jet charters save your time and give you comfort.
          </p>

        </div>

        <ul class="footer-list">

          <li>
            <p class="footer-list-title">Explore</p>
          </li>

          <li>
            <a href="{% url 'management:index' %}" class="footer-link">Home</a>
          </li>

          <li>
            <a href="{% url 'management:airports' %}" class="footer-link">Airports</a>
          </li>

          <li>
            <a href="{% url 'management:planes' %}" class="footer-link">Planes</a>
          </li>

          <li>
            <a href="{% url 'management:staff' %}" class="footer-link">Staff</a>
          </li>

          <li>
            <a href="{% url 'management:flights' %}" class="footer-link">Flights</a>
          </li>

        </ul>

        <ul class="footer-list">

          <li>
            <p class="footer-list-title">Links</p>
          </li>

          <li>
            <a href="#" class="footer-link">Terms of Use</a>
          </li>

          <li>
            <a href="#" class="footer-link">Contact</a>
          </li>

          <li>
            <a href="#" class="footer-link">News & Press</a>
          </li>

          <li>
            <a href="#" class="footer-link">FAQs</a>
          </li>

        </ul>

        <ul class="footer-list">

          <li>
            <p class="footer-list-title">Contact</p>
          </li>

          <li class="footer-list-item">
            <ion-icon name="call" aria-hidden="true"></ion-icon>

            <a href="tel: +353851112233" class="footer-link">+353 (85) 111 2233</a>
          </li>

          <li class="footer-list-item">
            <ion-icon name="mail" aria-hidden="true"></ion-icon>

            <a href="mailto:info@skyway.com" class="footer-link">info@skyway.com</a>
          </li>

          <li class="footer-list-item">
            <ion-icon name="location" aria-hidden="ture"></ion-icon>

            <address class="address">
              Dublin, Ireland
            </address>
          </li>

        </ul>

      </div>

      <div class="footer-bottom">

        <p class="copyright">
          Copyright 2025 by Viacheslav Nykonenko.
        </p>

        <ul class="social-list">

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-twitter"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-facebook"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-pinterest"></ion-icon>
            </a>
          </li>

          <li>
            <a href="#" class="social-link">
              <ion-icon name="logo-instagram"></ion-icon>
            </a>
          </li>

        </ul>

      </div>

    </div>
  </footer>

  <!--
    - #BACK TO TOP
  -->

  <a href="#top" class="back-top-btn" aria-label="back to top" data-back-top-btn>
    <ion-icon name="arrow-up-outline" aria-hidden="true"></ion-icon>
  </a>


  <!--
    - custom js link
  -->
  <script src="{% static 'js/script.js' %}" defer></script>

  <!--
    - ion-icon link
  -->
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</main>
</body>
</html>